#!/usr/bin/env bash
set -xeuo pipefail

NODE_ENV=${NODE_ENV:''}
if [[ "${NODE_ENV}" = "" ]]; then
	echo "NODE_ENV not set, assuming 'development'"
	export NODE_ENV=development
fi

if [[ "${NODE_ENV}" = "development" ]]; then
	export DATABASE_URL=$(heroku config:get DATABASE_URL)
	echo "Starting development server"
	npx concurrently --prefix name --names express,parcel --prefix-colors cyan,green --kill-others 'npx nodemon -w server/ -w package-lock.json -V server/server.js' 'npx parcel watch --hmr-port 9999 -- client/html/*.html'
elif [[ "${NODE_ENV}" = "production" ]]; then
	echo "Starting production server"
	node server/server.js
else
	echo "Unknown NODE_ENV value; must be either 'development' or 'production'. Aborting"
	exit 1
fi
